endereco/urls.py
from django.urls import path
from .views import AdrressCreate, AddressList, AddressUpdate, AddressDelete

app_name = 'endereco'

urlpatterns = [
    path('create/', AdrressCreate.as_view() , name='criar')
    path('listar/', AddressList.as_view() , name='listar')
    path('delete/<int:pk>/', AddressDelete.as_view() , name='deletar')
    path('update/<int:pk>/', AddressUpdate.as_view() , name='atualizar')
    path('detail/<int:pk>/', AddressDetail.as_view() , name='detalhar')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('endereco.urls'))
]

endereco/models.py
from django.db import models

# Create your models here.
from django.db import models

class Adrress(models.Model):
    cep = models.CharField(max_length=9)
    logradouro = models.CharField(max_length=50)
    bairro = models.CharField(max_length=30)
    localidade = models.CharField(max_length=30)
    uf = models.CharField(max_length=2)

endereco/forms.py
from django import forms
from .models import Adrress

class CepForm(forms.ModelForm):




class AdrressForm(forms.ModelForm):
    class Meta:
        model = Adrress
        fields =['cep', 'logradouro', 'bairro', 'localidade', 'uf']
        labels = {
            'cep': 'CEP',
            'logradouro': 'Logradouro',
            'bairro': 'Bairro',
            'localidade': 'Localidade',
            'uf': 'UF'
        }
        widgets = {
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'localidade': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'})
        }

endereco/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy

from .models import Adrress
from .forms import AdrressForm, CepForm
import requests

def cep_search_view(request):
    if request.method == 'get':
        form = CepForm()

    message = ''

    if request.method == 'POST':
        form = CepForm(request.POST)
        
        cep_digitado = request.POST.get('cep')
        url = f"https://viacep.com.br/ws/{cep_digitado}/json/"
        response = request.get(url)


        if response.status_code == 200:
            dados_cep = response.json()
            if 'erro' not in dados_cep:
                message = 'CEP encontrado'
            else:
                resposta_em_json_filtrada = (
                'cep' : dados_cep['cep'],
                'logradouro' : dados_cep['logradouro'],
                'bairro' : dados_cep['bairro'],
                'localidade' : dados_cep['localidade'],
                'uf' : dados_cep['uf']
                )
                form = CepForm(resposta_em_json_filtrada)

                if form.is_valid():
                    address = form.save(commit=False)
                    address.save
                    form.save()
        else:
            message = "Erro durante a api"
    return render (request, 'endereco/cep.html', {'form': form, 'message': message})

        

class AdrressCreate(CreateView):
    model = Adrress
    form_class = AdrressForm
    context_object_name = 'CreateAdrressform'
    template_name = 'endereco/addressForm.html'
    success_url = reverse_lazy('endereco:list')

class AddressList(ListView):
    model = Adrress
    template_name = 'endereco/address_list.html'
    context_object_name = 'addresses'

    class AddressUpdate(UpdateView):
        model = Adrress
        form_class = AdrressForm
        context_object_name = 'address'
        template_name = 'endereco/addressForm.html'
        sueccess_url = reverse_lazy('endereco:listar')

    class AddressDetail(DetailView):
        model = Adrress
        template_name = 'endereco/address_confirm_delete.html'
        context_object_name = 'address'
        
    class AddressDelete(DeleteView):
        model = Adrress
        template_name = 'endereco/address_confirm_delete.html'
        success_url = reverse_lazy('endereco:listar')
        
        

   

endereco/templates/endereco/addressDelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Remover</title>
</head>
<body>
    <h1>Comfirme a remoção</h1>
    <form action="{% url 'endereco:deletar' address.id %}" method="post">
        {% csrf_token %}
        <p>CEP: {{ address.cep }}</p>


        <button><a href="{% url ''}"></a></button>
    </form>
</body>
</html>

endereco/templates/endereco/addressDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes</title>
</head>
<body>
    <h1>Detalhes</h1>
    <p>CEP: {{ address.CEP }}</p>
    <p>Logradouro: {{ address.logradouro }}</p>
    <p>Bairro: {{ address.bairro }}</p>
    <p>Cidade: {{ address.localidade }}</p>
    <p>UF: {{ address.uf }}</p>

    <button><a href="{% url 'endereco:atualizar' address.id %}">Editar</a></button>
    <button><a href="{% url 'endereco:deletar' address.id %}">Remover</a></button>

</body>
</html>

endereco/templates/endereco/addressForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
    {% if address %}
    <h1> Editar</h1>
    <form action="{% url 'endereco:atualizar' address.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.label_tag }}
        <br>
        {{ field }}
        <br>
        {% endfor %}
        <button type="submit">Atualizar</button>
    </form>

    <h1>Cadastrar Endereço</h1>
    <form action="{% url 'endereco:criar' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        {{ field.label_tag }}
        <br>
        {{ field }}
        <br>
        {% endfor %}
        <button type="submit">Cadastrar</button>
    </form>
</body>
</html>

endereco/templates/endereco/addressList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>list</title>
</head>
<body>
    {% if addresses %}
    <h1> Endereços</h1>
    <table>
        <tr>
            <th>CEP</th>
            <th>Cidade</th>
            <th>UF</th>
        </tr>
        {% for address in addresses %}
        <tr>
            <td>{{ address.cep }}</td>
            <td>{{ address.localidade }}</td>
            <td>{{ address.uf }}</td>
            <td>
            <button><a href="{% url 'endereco:atualizar' address.id %}">Editar</a></button>
            <button><a href="{% url 'endereco:detalhar' address.id %}">Detalhes</a></button>
        </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    <h1>Nenhum endereço cadastrado</h1>
</body>
</html>

endereco/templates/endereco/cepSearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar e Salva Cep</title>
</head>
<body>
    <h1>Digite o CEP para busca</h1>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}

    <form method="post"></form>
    {% csrf_token %}

    { if not form.initial.logradouro %}
        <p>{{ form.cep.label.tag }}</p>
        <br>
        <p>{{ form.cep }}</p>
        <button type="submit">Buscar</button>

    {% else %}
        {{ form.as_p }}
        {% endif %}
</body>
</html>